# Generated by Django 2.1.2 on 2018-10-27 12:36

import Etudiant.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['domaine'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['Nom'],
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=Etudiant.models.renameSujet)),
                ('date', models.DateField(verbose_name='Quel année ?:')),
                ('date_d_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumision')),
                ('affichable', models.IntegerField(default=0, verbose_name='Affichabilité')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.Cours')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.Domaine')),
            ],
            options={
                'verbose_name': 'Sujet',
                'verbose_name_plural': 'Sujets',
                'ordering': ['domaine'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.Domaine'),
        ),
    ]
