# Generated by Django 2.1.2 on 2018-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='affichable',
            field=models.BooleanField(default=0, verbose_name='Affichabilité'),
        ),
    ]
