# Generated by Django 2.1.2 on 2018-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_auto_20181108_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='nom',
            field=models.CharField(default='Algorithme', max_length=100),
            preserve_default=False,
        ),
    ]
